/*Ejercicio 1 guía SQL
*/

SELECT * FROM EMPLEADOS;

SELECT * FROM DEPARTAMENTOS;

SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS;

SELECT NOMBRE, SALARIO FROM EMPLEADOS;

SELECT COMISION FROM EMPLEADOS;

SELECT NOMBRE FROM EMPLEADOS
WHERE EMPLEADOS.CARGO='SECRETARIA';

SELECT NOMBRE FROM EMPLEADOS
WHERE EMPLEADOS.CARGO='VENDEDOR'
ORDER BY NOMBRE ASC;

SELECT NOMBRE, CARGO, SALARIO 
FROM EMPLEADOS
ORDER BY SALARIO ASC;

SELECT NOMBRE, CARGO
FROM EMPLEADOS AS E;

SELECT SALARIO, COMISION
FROM EMPLEADOS AS E, DEPARTAMENTOS AS D
WHERE E.ID_DEPTO=2000
ORDER BY  E.COMISION ASC;

SELECT (SALARIO+COMISION)
FROM EMPLEADOS AS E
WHERE E.ID_DEPTO=3000
ORDER BY E.NOMBRE ASC;
/*
SELECT NOMBRE, COUNT(*)
FROM EMPLEADOS AS E
WHERE E.ID_DEPTO=3000; 
*/
SELECT NOMBRE
FROM EMPLEADOS AS E
WHERE SUBSTRING(E.NOMBRE,0)='J';

SELECT nombre FROM empleado WHERE nombre LIKE'J%';

SELECT SALARIO, COMISION, (SALARIO+COMISION), NOMBRE
FROM EMPLEADOS AS E
WHERE E.COMISION>1000;

SELECT SALARIO, COMISION, (SALARIO+COMISION), NOMBRE
FROM EMPLEADOS AS E
WHERE E.COMISION>=0;

SELECT NOMBRE, SALARIO, COMISION
FROM EMPLEADOS AS E
WHERE E.COMISION>E.SALARIO;

SELECT NOMBRE
FROM EMPLEADOS AS E
WHERE E.COMISION<=(E.SALARIO*0.3);

SELECT NOMBRE 
FROM EMPLEADOS AS E
WHERE E.NOMBRE NOT LIKE '%MA%';

SELECT NOMBRE_DEPTO 
FROM DEPARTAMENTOS AS D
WHERE D.NOMBRE_DEPTO!= 'VENTAS' 
AND D.NOMBRE_DEPTO!= 'INVESTIGACION' 
AND D.NOMBRE_DEPTO!= 'MANTENIMIENTO';

SELECT MAX(SALARIO)
FROM EMPLEADOS;

SELECT NOMBRE
FROM EMPLEADOS AS E
ORDER BY E.NOMBRE DESC;

SELECT MAX(SALARIO),MIN(SALARIO),(MAX(SALARIO)-MIN(SALARIO))
FROM EMPLEADOS;

SELECT AVG(SALARIO)
FROM EMPLEADOS;

SELECT stddev(SALARIO), std(SALARIO)
FROM EMPLEADOS;
