USE nba;
SELECT NOMBRE
FROM JUGADOR
ORDER BY NOMBRE ASC;


SELECT NOMBRE
FROM JUGADOR AS J 
WHERE J.POSICION='C' AND J.PESO>200
ORDER BY NOMBRE ASC;

SELECT NOMBRE
FROM EQUIPO AS E
ORDER BY NOMBRE ASC;

SELECT NOMBRE 
FROM EQUIPO AS E
WHERE E.CONFERENCIA='EAST';

SELECT NOMBRE
FROM EQUIPO AS E
WHERE E.NOMBRE LIKE 'C%'
ORDER BY NOMBRE;

SELECT NOMBRE, NOMBRE_EQUIPO
FROM JUGADOR AS J
ORDER BY NOMBRE_EQUIPO;

SELECT NOMBRE
FROM JUGADOR AS J
WHERE J.NOMBRE_EQUIPO='RAPTORS'
ORDER BY NOMBRE;

SELECT PUNTOS_POR_PARTIDO
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE J.NOMBRE='PAU GASOL';

SELECT PUNTOS_POR_PARTIDO, COUNT(*)
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE J.NOMBRE='PAU GASOL';

SELECT PUNTOS_POR_PARTIDO, COUNT(*)
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE J.NOMBRE='PAU GASOL' AND TEMPORADA='04/05';

SELECT COUNT(E.PUNTOS_POR_PARTIDO), J.NOMBRE
FROM ESTADISTICA AS E, JUGADOR AS J
GROUP BY J.NOMBRE
ORDER BY NOMBRE ASC;

SELECT J.NOMBRE, E.NOMBRE
FROM JUGADOR AS J, EQUIPO AS E
GROUP BY E.NOMBRE;


SELECT NOMBRE
FROM JUGADOR AS J, ESTADISTICA AS E
WHERE E.PUNTOS_POR_PARTIDO=(SELECT PUNTOS_POR_PARTIDO FROM ESTADISTICA WHERE PUNTOS_POR_PARTIDO=MAX(PUNTOS_POR_PARTIDO));

SELECT NOMBRE, CONFERENCIA, DIVISION
FROM EQUIPO AS E, JUGADOR AS J
WHERE E.NOMBRE=J.NOMBRE_EQUIPO;

SELECT E.NOMBRE, E.CONFERENCIA, E.DIVISION
FROM EQUIPO AS E, JUGADOR AS J
WHERE E.NOMBRE=J.NOMBRE_EQUIPO AND J.ALTURA=(SELECT MAX(J.ALTURA))
GROUP BY E.NOMBRE;
SELECT *
FROM PARTIDO
LIMIT 1;



SELECT AVG(PUNTOS_POR_PARTIDO)
FROM ESTADISTICA AS E, EQUIPO AS EQ
WHERE EQ.DIVISION='PACIFIC';

SELECT MAX(PUNTOS_LOCAL-PUNTOS_VISITANTE)
FROM PARTIDO;

SELECT AVG((PUNTOS_LOCAL+PUNTOS_VISITANTE))
FROM PARTIDO AS P, EQUIPO AS E
WHERE E.DIVISION='PACIFIC';

SELECT CODIGO, EQUIPO_LOCAL, EQUIPO_VISITANTE
FROM PARTIDO;