USE nba;

SELECT MAX(ASISTENCIAS_POR_PARTIDO)
FROM ESTADISTICA;

SELECT COUNT(ASISTENCIAS_POR_PARTIDO)
FROM ESTADISTICA
WHERE ASISTENCIAS_POR_PARTIDO>=34;

SELECT NOMBRE 
FROM EQUIPO AS E
WHERE E.CONFERENCIA='EAST';

SELECT DISTINCT POSICION 
FROM JUGADOR;

SELECT SUM(PESO)
FROM JUGADOR AS J
WHERE J.NOMBRE_EQUIPO IN ('76ERS','BOBCATS','BUCKS','BULLS','CAVALIERS','CELTICS','HAWKS','HEAT','KNICKS','MAGIC','NETS','PACERS','PISTONS','RAPTORS','WIZARDS') 
AND J.POSICION IN ('C','C-F','F-C');

SELECT COUNT(NOMBRE)
FROM JUGADOR AS J
WHERE J.NOMBRE_EQUIPO='HEAT';

SELECT COUNT(JUGADOR)
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE E.ASISTENCIAS_POR_PARTIDO>16;

SELECT DISTINCT *
FROM ESTADISTICA AS E
WHERE E.ASISTENCIAS_POR_PARTIDO>16;

SELECT DISTINCT TEMPORADA
FROM PARTIDO AS P;

SELECT COUNT(EQUIPO_LOCAL)
FROM PARTIDO AS P
WHERE P.TEMPORADA IN ('98/99','99/00');

SELECT NOMBRE 
FROM EQUIPO AS E
WHERE E.CONFERENCIA='WEST';

SELECT DISTINCT COUNT(NOMBRE)
FROM JUGADOR AS J
WHERE J.PROCEDENCIA='MICHIGAN' AND J.NOMBRE_EQUIPO IN ('CLIPPERS','GRIZZLIES','HORNETS','JAZZ','KINGS','LAKERS','MAVERICKS','NUGGETS','ROCKETS','SPURS','SUNS','SUPERSONICS','TIMBERWOLVES','TRAIL BLAZERS','WARRIORS');

SELECT COUNT(NOMBRE)
FROM JUGADOR AS J
WHERE J.PESO>=195;

SELECT NOMBRE
FROM EQUIPO
WHERE EQUIPO.DIVISION='CENTRAL';


SELECT AVG(PUNTOS_POR_PARTIDO)
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE E.JUGADOR=J.CODIGO
AND J.NOMBRE_EQUIPO IN ('BUCKS', 'BULLS','CAVALIERS','PACERS','PISTONS');

SELECT COUNT(ASISTENCIAS_POR_PARTIDO)
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE E.JUGADOR=J.CODIGO
AND J.NOMBRE_EQUIPO IN ('BUCKS', 'BULLS','CAVALIERS','PACERS','PISTONS');

SELECT SUM(TAPONES_POR_PARTIDO)
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE E.JUGADOR=J.CODIGO
AND J.NOMBRE_EQUIPO IN ('BUCKS', 'BULLS','CAVALIERS','PACERS','PISTONS');


/*Para obtener el siguiente código deberás redondear hacia abajo el resultado que se
devuelve de sumar: el promedio de puntos por partido, el conteo de asistencias por partido,
y la suma de tapones por partido. Además, este resultado debe ser, donde la división sea
central. BUCKS, BULLS,CAVALIERS,PACERS,PISTONS.9.699348967522383, 384, 237.64000104740262

*/



SELECT DISTINCT PROCEDENCIA
FROM JUGADOR;

SELECT ROUND(SUM(PUNTOS_POR_PARTIDO))
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE J.CODIGO IN (86,231,352,366,370,545);

SELECT ROUND(SUM(PUNTOS_POR_PARTIDO))
FROM ESTADISTICA AS E, JUGADOR AS J
WHERE J.CODIGO = E.JUGADOR
AND J.CODIGO IN (86,231,352,366,370,545);


SELECT *
FROM JUGADOR
WHERE JUGADOR.PROCEDENCIA='ARGENTINA';

